#DEPLOYMENT DEFINITION FOR REST02
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest02-prodv01-dep  
  labels:
    app: rest02       #XXX
spec:
  replicas: 4
  selector:
    matchLabels:
      app: rest02    #XXX
  template:
    metadata:
      labels:
        app: rest02   #XXX
    spec:
      volumes:
        - name: makerest02
          nfs:
            ip: 10.1.4.10
            path: /temp-app/rest02
            type: Directory
      containers:
      - name: rest02  
        image: dockerkarelh/kdh-rest02-prodv01
        ports:
        - containerPort: 5002 #the standard 80 port
        volumeMounts:
         - name: makerest02
           mountPath: /restservice/
#dit betekent hier komt een nieuwe YAML-file
---

#SERVICE DEFINITION FOR REST02  
apiVersion: v1
kind: Service
metadata:
  name: rest02-prodv01-serv  
spec:
  selector: #om te linken naar een Deployment
    app: rest02      #XXX
  type: LoadBalancer  
  ports:
    - protocol: TCP
      port: 5052  #de pod open poort 5002 als connectie
      targetPort: 5002
      #setting2 voor een external toegang
      nodePort: 30502  #moet tussen 30000 en 32767 liggen
